version: "3.7"

services:
  chrome:
    image: seleniarm/node-chromium:4.1.2-20220227
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - ${PORT_CHROME}:5900
      - ${VNC_PORT_CHROME}:5900 # for vnc

  firefox:
    image: seleniarm/node-firefox:4.1.2-20220227
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - ${PORT_FIREFOX}:5900
      - ${VNC_PORT_FIREFOX}:5900 # for vnc

  seleniarm-hub:
    image: seleniarm/hub:4.1.2-20220227
    ports:
      - ${SELENIARM_PORT_4442}:4442
      - ${SELENIARM_PORT_4443}:4443
      - ${SELENIARM_PORT_4444}:4444
