services:
  httpd:
    image: in2code/httpd:2.4-alpine
    environment:
      WEB_DOCUMENT_ROOT: /app/${WEBROOT}/
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
    volumes:
      - ./:/app/:cached
    networks:
      default:
        aliases:
          - ${HOST}

  php:
    build:
      context: .project/docker/php/
      dockerfile: Dockerfile
    volumes:
      - ./:/app/:cached
      - $HOME/.composer/auth.json:/tmp/composer/auth.json
      - $HOME/.composer/cache/:/tmp/composer/cache/
    env_file:
      - .env
      - .env.local

  mysql:
    image: in2code/mysql:8.0
    env_file:
      - .env
      - .env.local
    volumes:
      - mysql:/var/lib/mysql/
      - ${SQLDUMPSDIR}:/${SQLDUMPSDIR}
    ports:
      - ${SQLPORT}:3306

  node:
    image: node:10
    user: node
    command: ["bash"]
    tty: true
    volumes:
      - ./:/home/node/app/
    working_dir: /home/node/app/Resources/Private

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_PORT: 8025
      VIRTUAL_HOST: ${MAIL}

  chrome:
    image: seleniarm/node-chromium:4.1.2-20220227
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - ${PORT_CHROME}:5900
      - ${VNC_PORT_CHROME}:5900 # for vnc

  firefox:
    image: seleniarm/node-firefox:4.1.2-20220227
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - ${PORT_FIREFOX}:5900
      - ${VNC_PORT_FIREFOX}:5900 # for vnc

  seleniarm-hub:
    image: seleniarm/hub:4.1.2-20220227
    ports:
      - ${SELENIARM_PORT_4442}:4442
      - ${SELENIARM_PORT_4443}:4443
      - ${SELENIARM_PORT_4444}:4444


volumes:
  mysql:
