<?php

return [
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'city',
        'value' => 'Rosenheim',
    ],
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'country',
        'value' => 'Germany',
    ],
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'countryCode',
        'value' => 'DE',
    ],
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lat',
        'value' => '47.8479687',
    ],
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lon',
        'value' => '12.1110311',
    ],
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'org',
        'value' => 'in2code GmbH',
    ],
    [
        'visitor' => 2,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'city',
        'value' => 'Nürnberg',
    ],
    [
        'visitor' => 2,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'country',
        'value' => 'Germany',
    ],
    [
        'visitor' => 2,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'countryCode',
        'value' => 'DE',
    ],
    [
        'visitor' => 2,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'org',
        'value' => 'Kellner AG - Best Snowboard Wear',
    ],
    [
        'visitor' => 2,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lat',
        'value' => '49.5313357',
    ],
    [
        'visitor' => 2,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lon',
        'value' => '11.011675',
    ],
    [
        'visitor' => 3,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'city',
        'value' => 'Stuttgart',
    ],
    [
        'visitor' => 3,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'countryCode',
        'value' => 'DE',
    ],
    [
        'visitor' => 3,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'country',
        'value' => 'Germany',
    ],
    [
        'visitor' => 3,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lat',
        'value' => '48.7773313',
    ],
    [
        'visitor' => 3,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lon',
        'value' => '9.1608973',
    ],
    [
        'visitor' => 4,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'city',
        'value' => 'Wien',
    ],
    [
        'visitor' => 4,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'countryCode',
        'value' => 'AT',
    ],
    [
        'visitor' => 4,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'country',
        'value' => 'Austria',
    ],
    [
        'visitor' => 4,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lat',
        'value' => '48.2225854',
    ],
    [
        'visitor' => 4,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lon',
        'value' => '16.3615076',
    ],
    [
        'visitor' => 5,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'city',
        'value' => 'Wien',
    ],
    [
        'visitor' => 5,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'countryCode',
        'value' => 'AT',
    ],
    [
        'visitor' => 5,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'country',
        'value' => 'Austria',
    ],
    [
        'visitor' => 5,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lat',
        'value' => '48.2225854',
    ],
    [
        'visitor' => 5,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lon',
        'value' => '16.3615076',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'city',
        'value' => 'Nürnberg',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'country',
        'value' => 'USA',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'countryCode',
        'value' => 'US',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'org',
        'value' => 'Wettbewerber Group',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lat',
        'value' => '49.5313357',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lon',
        'value' => '11.011675',
    ],
    [
        'visitor' => 7,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'city',
        'value' => 'Nürnberg',
    ],
    [
        'visitor' => 7,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'country',
        'value' => 'USA',
    ],
    [
        'visitor' => 7,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'countryCode',
        'value' => 'US',
    ],
    [
        'visitor' => 7,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'org',
        'value' => 'TV streaming company',
    ],
    [
        'visitor' => 7,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lat',
        'value' => '49.5313357',
    ],
    [
        'visitor' => 7,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lon',
        'value' => '11.011675',
    ],
    [
        'visitor' => 8,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'city',
        'value' => 'St. Gallen',
    ],
    [
        'visitor' => 8,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'country',
        'value' => 'Switzerland',
    ],
    [
        'visitor' => 8,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'countryCode',
        'value' => 'CH',
    ],
    [
        'visitor' => 8,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lat',
        'value' => '47.4241067',
    ],
    [
        'visitor' => 8,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lon',
        'value' => '9.3221825',
    ],
];
