<?php

return [
    [
        'uid' => 1,
        'title' => 'in2code GmbH',
        'branch_code' => 62,
        'city' => 'Rosenheim',
        'contacts' => json_encode([['first' => 'Stefan', 'last' => 'Busemann', 'pos' => 'CFO', 'sal' => 'Herr']]),
        'continent' => 'eu',
        'country_code' => 'de',
        'region' => 'Bayern',
        'street' => 'Kunstmühlstr. 12a',
        'zip' => 83026,
        'domain' => 'in2code.de',
        'founding_year' => 2010,
        'phone' => '08031 8873983',
        'revenue' => '2.500.001 bis 5.000.000 Euro',
        'revenue_class' => '05',
        'size' => '20 - 49 Beschäftigte',
        'size_class' => '04',
        'description' => '',
        'crdate' => (new DateTime('31 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime())->getTimestamp(),
    ],
    [
        'uid' => 2,
        'title' => 'Kellner Logistics GmbH & Co. KG',
        'branch_code' => 53,
        'city' => 'Nürnberg',
        'contacts' => json_encode([['first' => 'Alexander', 'last' => 'Kellner', 'pos' => 'Geschäftsführender Gesellschafter', 'sal' => 'Herr']]),
        'continent' => 'eu',
        'country_code' => 'de',
        'region' => 'Bayern',
        'street' => 'Volkacherstr. 123',
        'zip' => 90427,
        'domain' => 'kellnerlogistics.de',
        'founding_year' => 1963,
        'phone' => '0123 4567891',
        'revenue' => '25.000.001 bis 50.000.000 Euro',
        'revenue_class' => '07',
        'size' => '200 - 499 Beschäftigte',
        'size_class' => '07',
        'description' => '',
        'crdate' => (new DateTime('47 days ago'))->modify('+ 555 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('47 days ago'))->modify('+ 555 minutes')->getTimestamp(),
    ],
    [
        'uid' => 3,
        'title' => 'Bad-Mainhoffer Klinikum AG',
        'branch_code' => 86,
        'city' => 'Stuttgart',
        'contacts' => json_encode([['first' => 'Heiko', 'last' => 'Huber', 'pos' => 'CEO', 'sal' => 'Herr']]),
        'continent' => 'eu',
        'country_code' => 'de',
        'region' => 'Baden-Württemberg',
        'street' => 'Stuttgarter Schiffstr. 123',
        'zip' => 70173,
        'domain' => 'powersli.de',
        'founding_year' => 2000,
        'phone' => '0123 4567891',
        'revenue' => '50.000.001 bis 500.000.000 Euro',
        'revenue_class' => '08',
        'size' => 'ab 2000 Beschäftigte',
        'size_class' => '10',
        'description' => '',
        'crdate' => (new DateTime('55 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('55 days ago'))->getTimestamp(),
    ],
    [
        'uid' => 4,
        'title' => 'Université De Vienna',
        'branch_code' => 72,
        'city' => 'Wien',
        'contacts' => json_encode([['first' => 'Max', 'last' => 'Muster', 'pos' => 'CEO', 'sal' => 'Herr']]),
        'continent' => 'eu',
        'country_code' => 'at',
        'region' => '',
        'street' => 'Wiener Allee 123',
        'zip' => 9876,
        'domain' => 'universitaet.at',
        'founding_year' => 1981,
        'phone' => '0123 4567891',
        'revenue' => '2.500.001 bis 5.000.000 Euro',
        'revenue_class' => '05',
        'size' => '500 - 999 Beschäftigte',
        'size_class' => '08',
        'description' => '',
        'crdate' => (new DateTime('130 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('130 days ago'))->getTimestamp(),
    ],
    [
        'uid' => 5,
        'title' => 'Umbrella Corporation',
        'branch_code' => 72,
        'city' => 'Darmstadt',
        'contacts' => json_encode([['first' => 'Alice', 'last' => 'Doe', 'pos' => 'CISO', 'sal' => 'Frau']]),
        'continent' => 'eu',
        'country_code' => 'de',
        'region' => '',
        'street' => 'Residente-Vil Weg',
        'zip' => 12345,
        'domain' => 'umbrella.com',
        'founding_year' => 2005,
        'phone' => '0123 4567891',
        'revenue' => 'über 500.000.000 Euro',
        'revenue_class' => '09',
        'size' => '500 - 999 Beschäftigte',
        'size_class' => '08',
        'description' => '',
        'crdate' => (new DateTime('55 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('55 days ago'))->getTimestamp(),
    ],
    [
        'uid' => 6,
        'title' => 'Wettbewerber AG',
        'branch_code' => 62,
        'city' => 'München',
        'contacts' => json_encode([['first' => 'Stefan', 'last' => 'Vielreicher', 'pos' => 'CEO', 'sal' => 'Herr']]),
        'continent' => 'eu',
        'country_code' => 'de',
        'region' => 'Bayern',
        'street' => 'Augsburger Str. 1',
        'zip' => 87654,
        'domain' => 'wettbewerber.ag',
        'founding_year' => 1990,
        'phone' => '0123 4567891',
        'revenue' => '500.001 bis 2.500.000 Euro',
        'revenue_class' => '04',
        'size' => '20 - 49 Beschäftigte',
        'size_class' => '04',
        'description' => 'Härtester Konkurrent in der Branche',
        'crdate' => (new DateTime('188 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('188 days ago'))->getTimestamp(),
    ],
    [
        'uid' => 7,
        'title' => 'Netprime Plus',
        'branch_code' => 93,
        'city' => 'Hamburg',
        'contacts' => json_encode([['first' => 'John', 'last' => 'Mc Cormick', 'pos' => 'CTO', 'sal' => 'Herr']]),
        'continent' => 'eu',
        'country_code' => 'de',
        'region' => 'Hamburg',
        'street' => 'Cheeseburger Str. 1',
        'zip' => 45678,
        'domain' => 'netprime.plus',
        'founding_year' => 2011,
        'phone' => '0123 4567891',
        'revenue' => '50.000.001 bis 500.000.000 Euro',
        'revenue_class' => '08',
        'size' => 'ab 2000 Beschäftigte',
        'size_class' => '10',
        'description' => '',
        'crdate' => (new DateTime('39 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('39 days ago'))->getTimestamp(),
    ],
    [
        'uid' => 8,
        'title' => 'University of Switzerland',
        'branch_code' => 72,
        'city' => 'Bern',
        'contacts' => json_encode([['first' => 'Max', 'last' => 'Muster', 'pos' => 'CEO', 'sal' => 'Herr']]),
        'continent' => 'eu',
        'country_code' => 'ch',
        'region' => '',
        'street' => 'Bernadiner Weg 12',
        'zip' => 1234,
        'domain' => 'university.ch',
        'founding_year' => 1923,
        'phone' => '0123 4567891',
        'revenue' => '2.500.001 bis 5.000.000 Euro',
        'revenue_class' => '05',
        'size' => '500 - 999 Beschäftigte',
        'size_class' => '08',
        'description' => '',
        'crdate' => (new DateTime('3 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('3 days ago'))->getTimestamp(),
    ],
    [
        'uid' => 9,
        'title' => 'Real Estate Professionals - REP',
        'branch_code' => 68,
        'city' => 'Darmstadt',
        'contacts' => json_encode([['first' => 'Max', 'last' => 'Müller', 'pos' => 'CEO', 'sal' => 'Herr']]),
        'continent' => 'eu',
        'country_code' => 'de',
        'region' => 'Hessen',
        'street' => 'Feststraße 123',
        'zip' => 65432,
        'domain' => 'rep.re',
        'founding_year' => 1999,
        'phone' => '0123 4567891',
        'revenue' => '5.000.001 bis 25.000.000 Euro',
        'revenue_class' => '06',
        'size' => '100 - 199 Beschäftigte',
        'size_class' => '06',
        'description' => '',
        'crdate' => (new DateTime('2 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('2 days ago'))->getTimestamp(),
    ],
];
