<?php

use In2code\Lux\Domain\Service\DemoDataService;
use In2code\Lux\Utility\StringUtility;

return [
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://cermat.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/100.0',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 4,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 5,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.55',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 124.0.0.11.473 (iPhone9,1; iOS 13_3; de_DE; de-DE; scale=2.00; 750x1334; 192646147)',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 7,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 124.0.0.11.473 (iPhone9,1; iOS 13_3; de_DE; de-DE; scale=2.00; 750x1334; 192646147)',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 8,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 9,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 10,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 11,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.55',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 12,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 124.0.0.11.473 (iPhone9,1; iOS 13_3; de_DE; de-DE; scale=2.00; 750x1334; 192646147)',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 13,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'domain' => 'https://www.in2code.de',
        'value' => StringUtility::getRandomString(32, false),
        'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
];
