<?php

return [
    [
        'tstamp' => (new DateTime('2 hours ago'))->modify('+ 34 minutes')->getTimestamp(),
        'crdate' => (new DateTime('2 hours ago'))->modify('+ 34 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'pagevisit' => 1,
        'referrer' => 'https://syndicatedsearch.goog',
        'utm_source' => 'google',
        'utm_medium' => 'google ads',
        'utm_campaign' => 'LUX Community Version',
        'utm_id' => 'llcv',
        'utm_term' => 'Marketing Automation',
        'utm_content' => 'Ad3',
    ],
    [
        'tstamp' => (new DateTime('2 days ago'))->modify('+ 34 minutes')->getTimestamp(),
        'crdate' => (new DateTime('2 days ago'))->modify('+ 34 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'pagevisit' => 12,
        'referrer' => 'https://www.instagram.com',
        'utm_source' => 'instagram',
        'utm_medium' => 'Instagram App',
        'utm_campaign' => 'Product A',
        'utm_id' => 'pa',
        'utm_term' => '',
        'utm_content' => '',
    ],
    [
        'tstamp' => (new DateTime('2 days ago'))->modify('+ 34 minutes')->getTimestamp(),
        'crdate' => (new DateTime('2 days ago'))->modify('+ 34 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'pagevisit' => 15,
        'referrer' => 'https://www.instagram.com',
        'utm_source' => 'instagram',
        'utm_medium' => 'Instagram App',
        'utm_campaign' => 'Product A',
        'utm_id' => 'pa',
        'utm_term' => '',
        'utm_content' => '',
    ],
];
