<?php

return [
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'email',
        'value' => 'stefan.busemann@in2code.de',
    ],
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'firstname',
        'value' => 'Stefan',
    ],
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lastname',
        'value' => 'Busemann',
    ],
    [
        'visitor' => 1,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'company',
        'value' => 'in2code GmbH',
    ],
    [
        'visitor' => 2,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'email',
        'value' => 'alex@kellner.com',
    ],
    [
        'visitor' => 2,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'firstname',
        'value' => 'Alex',
    ],
    [
        'visitor' => 3,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'email',
        'value' => 'sandra.pohl@gmail.com',
    ],
    [
        'visitor' => 4,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'email',
        'value' => 'max.muster@university.de',
    ],
    [
        'visitor' => 5,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'email',
        'value' => 'john.doe@umbrella.com',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'email',
        'value' => 'richter.david@wettbewerber.org',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'firstname',
        'value' => 'David',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'lastname',
        'value' => 'Richter',
    ],
    [
        'visitor' => 6,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'newsletter',
        'value' => '1',
    ],
    [
        'visitor' => 9,
        'tstamp' => (new DateTime())->getTimestamp(),
        'crdate' => (new DateTime())->getTimestamp(),
        'sys_language_uid' => -1,
        'name' => 'company',
        'value' => 'Real Estate Professionals',
    ],
];
