<?php

use In2code\Lux\Domain\Model\Log;
use In2code\Lux\Domain\Service\DemoDataService;

return [
    [
        'visitor' => 1,
        'status' => Log::STATUS_NEW,
        'tstamp' => (new DateTime('31 days ago'))->getTimestamp(),
        'crdate' => (new DateTime('31 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_UTM_TRACK,
        'tstamp' => (new DateTime('22 hours ago'))->getTimestamp(),
        'crdate' => (new DateTime('22 hours ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['utm' => 1]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_SEARCH,
        'tstamp' => (new DateTime('22 days ago'))->modify('+ 450 minutes')->getTimestamp(),
        'crdate' => (new DateTime('22 days ago'))->modify('+ 450 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['search' => 1]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_IDENTIFIED_EMAIL4LINK,
        'tstamp' => (new DateTime('12 hours ago'))->getTimestamp(),
        'crdate' => (new DateTime('12 hours ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_LINKLISTENER,
        'tstamp' => (new DateTime('10 hours ago'))->modify('+ 77 minutes')->getTimestamp(),
        'crdate' => (new DateTime('10 hours ago'))->modify('+ 77 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'linklistener' => 1,
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
         ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_LINKLISTENER,
        'tstamp' => (new DateTime('3 days ago'))->modify('+ 54 minutes')->getTimestamp(),
        'crdate' => (new DateTime('3 days ago'))->modify('+ 54 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'linklistener' => 2,
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
         ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_DOWNLOAD,
        'tstamp' => (new DateTime('1 hours ago'))->modify('+ 333 minutes')->getTimestamp(),
        'crdate' => (new DateTime('1 hours ago'))->modify('+ 333 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['href' => '/fileadmin/whitepapers/producta.pdf']),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_LINKLISTENER,
        'tstamp' => (new DateTime('1234 hours ago'))->getTimestamp(),
        'crdate' => (new DateTime('1234 hours ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'linklistener' => 3,
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_SHORTENER_VISIT,
        'crdate' => (new DateTime('4 days ago'))->modify('+342 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('4 days ago'))->modify('+342 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'path' => '/landingpage',
            'shortenervisit' => 1,
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 2 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 2 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 20 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 20 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 40 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 40 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 80 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 80 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 100 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 100 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 120 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 120 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 140 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 140 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 160 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 160 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 1,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 180 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 180 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_NEW,
        'tstamp' => (new DateTime('47 days ago'))->modify('+ 555 minutes')->getTimestamp(),
        'crdate' => (new DateTime('47 days ago'))->modify('+ 555 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_IDENTIFIED_FORMLISTENING,
        'tstamp' => (new DateTime('47 days ago'))->modify('+ 556 minutes')->getTimestamp(),
        'crdate' => (new DateTime('47 days ago'))->modify('+ 556 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_DOWNLOAD,
        'tstamp' => (new DateTime('6 days ago'))->modify('+ 70 minutes')->getTimestamp(),
        'crdate' => (new DateTime('6 days ago'))->modify('+ 70 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['href' => '/fileadmin/whitepapers/producta.pdf']),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_DOWNLOAD,
        'tstamp' => (new DateTime('6 days ago'))->modify('+ 78 minutes')->getTimestamp(),
        'crdate' => (new DateTime('6 days ago'))->modify('+ 78 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['href' => '/fileadmin/whitepapers/productb.pdf']),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_ACTION,
        'tstamp' => (new DateTime('6 days ago'))->modify('+ 79 minutes')->getTimestamp(),
        'crdate' => (new DateTime('6 days ago'))->modify('+ 79 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_IDENTIFIED_FORMLISTENING,
        'tstamp' => (new DateTime('2 days ago'))->modify('+ 123 minutes')->getTimestamp(),
        'crdate' => (new DateTime('2 days ago'))->modify('+ 123 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_SHORTENER_VISIT,
        'crdate' => (new DateTime('14 days ago'))->modify('+542 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('14 days ago'))->modify('+542 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'path' => '/blogpost',
            'shortenervisit' => 2,
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 12 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 12 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 32 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 32 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 52 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 52 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 72 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 72 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 92 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 92 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 112 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 112 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 132 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 132 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 2,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 152 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 152 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('55 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('55 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_DOWNLOAD,
        'crdate' => (new DateTime('55 days ago'))->modify('+ 4 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('55 days ago'))->modify('+ 4 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['href' => '/fileadmin/whitepapers/producta.pdf']),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_LINKLISTENER,
        'tstamp' => (new DateTime('2345 hours ago'))->getTimestamp(),
        'crdate' => (new DateTime('2345 hours ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'linklistener' => 1,
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_SHORTENER_VISIT,
        'crdate' => (new DateTime('2 days ago'))->modify('+678 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('2 days ago'))->modify('+678 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'path' => '/blogpost',
            'shortenervisit' => 2,
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('3 days ago'))->modify('+ 152 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('3 days ago'))->modify('+ 152 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('3 days ago'))->modify('+ 172 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('3 days ago'))->modify('+ 172 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('3 days ago'))->modify('+ 222 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('3 days ago'))->modify('+ 222 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('3 days ago'))->modify('+ 252 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('3 days ago'))->modify('+ 252 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('3 days ago'))->modify('+ 312 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('3 days ago'))->modify('+ 312 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 3,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('3 days ago'))->modify('+ 545 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('3 days ago'))->modify('+ 545 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 4,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('130 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('130 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 4,
        'status' => Log::STATUS_DOWNLOAD,
        'crdate' => (new DateTime('130 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('130 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['href' => '/fileadmin/whitepapers/productc.pdf']),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 4,
        'status' => Log::STATUS_IDENTIFIED_EMAIL4LINK,
        'crdate' => (new DateTime('130 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('130 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 4,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('1 days ago'))->modify('+ 543 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+ 543 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 4,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('4 days ago'))->modify('+ 10 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('4 days ago'))->modify('+ 10 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 4,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('4 days ago'))->modify('+ 40 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('4 days ago'))->modify('+ 40 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 4,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('4 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('4 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 5,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('55 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('55 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 5,
        'status' => Log::STATUS_DOWNLOAD,
        'crdate' => (new DateTime('55 days ago'))->modify('+ 10 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('55 days ago'))->modify('+ 10 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['href' => '/fileadmin/whitepapers/producta.pdf']),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 5,
        'status' => Log::STATUS_IDENTIFIED_EMAIL4LINK,
        'crdate' => (new DateTime('55 days ago'))->modify('+ 30 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('55 days ago'))->modify('+ 30 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 5,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('5 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('5 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 5,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('5 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('5 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 6,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('188 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('188 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 6,
        'status' => Log::STATUS_DOWNLOAD,
        'crdate' => (new DateTime('188 days ago'))->modify('+ 5 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('188 days ago'))->modify('+ 5 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['href' => '/fileadmin/whitepapers/producta.pdf']),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 6,
        'status' => Log::STATUS_IDENTIFIED_EMAIL4LINK,
        'crdate' => (new DateTime('188 days ago'))->modify('+ 7 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('188 days ago'))->modify('+ 7 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'pageUid' => DemoDataService::getRandomPageIdentifier(),
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 6,
        'status' => Log::STATUS_DOWNLOAD,
        'crdate' => (new DateTime('6 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('6 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['href' => '/fileadmin/whitepapers/productb.pdf']),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 7,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('39 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('39 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 7,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('39 days ago'))->modify('+ 543 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('39 days ago'))->modify('+ 543 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 7,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('39 days ago'))->modify('+ 545 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('39 days ago'))->modify('+ 545 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 7,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('39 days ago'))->modify('+ 548 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('39 days ago'))->modify('+ 548 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 8,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('3 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('3 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 8,
        'status' => Log::STATUS_DOWNLOAD,
        'crdate' => (new DateTime('3 days ago'))->modify('+ 8 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('3 days ago'))->modify('+ 8 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode(['href' => '/fileadmin/whitepapers/productb.pdf']),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 8,
        'status' => Log::STATUS_SHORTENER_VISIT,
        'crdate' => (new DateTime('2 days ago'))->modify('+12 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('2 days ago'))->modify('+12 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'path' => '/blogpost',
            'shortenervisit' => 2,
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 9,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('2 days ago'))->getTimestamp(),
        'tstamp' => (new DateTime('2 days ago'))->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 10,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('1 days ago'))->modify('+3 hours')->getTimestamp(),
        'tstamp' => (new DateTime('1 days ago'))->modify('+3 hours')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 11,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('4 hours ago'))->modify('+12 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('4 hours ago'))->modify('+12 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 12,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('3 hours ago'))->modify('+32 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('3 hours ago'))->modify('+32 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 13,
        'status' => Log::STATUS_NEW,
        'crdate' => (new DateTime('12 days ago'))->modify('+7 hours')->getTimestamp(),
        'tstamp' => (new DateTime('12 days ago'))->modify('+7 hours')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => '',
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 13,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('12 days ago'))->modify('+ 22 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('12 days ago'))->modify('+ 22 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 13,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('10 days ago'))->modify('+ 567 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('10 days ago'))->modify('+ 567 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
    [
        'visitor' => 13,
        'status' => Log::STATUS_ACTION,
        'crdate' => (new DateTime('6 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'tstamp' => (new DateTime('6 days ago'))->modify('+ 60 minutes')->getTimestamp(),
        'sys_language_uid' => -1,
        'properties' => json_encode([
            'workflowUid' => DemoDataService::getRandomWorkflowIdentifier(),
            'workflowTitle' => DemoDataService::getRandomWorkflowTitle(),
            'actionUid' => 1,
            'actionTitle' => 'Dummy Action',
        ]),
        'site' => DemoDataService::getRandomSiteIdentifier(),
    ],
];
