name: TER release

on:
  push:
    tags:
      - '*'

jobs:
  ter-release:
    name: TER release
    runs-on: ubuntu-latest
    env:
      TYPO3_EXTENSION_KEY: 'lux'
      REPOSITORY_URL: 'https://github.com/in2code-de/lux'
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
      TYPO3_API_USERNAME: ${{ secrets.TYPO3_API_USERNAME }}
      TYPO3_API_PASSWORD: ${{ secrets.TYPO3_API_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl, mbstring, xml, soap, zip, curl
          tools: composer:v2

      - name: Install EXT:tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress

      - name: Set version number in ext_emconf.php
        run: php ~/.composer/vendor/bin/tailor set-version ${{ steps.get_version.outputs.VERSION }}

      - name: Upload EXT:${{ env.TYPO3_EXTENSION_KEY }} as ${{ steps.get_version.outputs.VERSION }} to TER
        run: php ~/.composer/vendor/bin/tailor ter:publish --comment="New release of version ${{ steps.get_version.outputs.VERSION }} - see details, changelog and documentation on ${{ env.REPOSITORY_URL }}" ${{ steps.get_version.outputs.VERSION }}
